#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -o /home/ryan/logs/${PBS_JOBNAME}.o${PBS_JOBID}.log
#PBS -e /home/ryan/logs/${PBS_JOBNAME}.e${PBS_JOBID}.err
#PBS -l walltime=150:00:00
#PBS -l mem=16gb

python2 /home/ryan/topmed/multiomic_modeling/topmed.py \
-i /home/ryan/topmed/multiomic_modeling/predictor_matrices/vcfs/CAU_PBMC_ \
-c ${chr} \
--cpos \
--outdir /home/ryan/topmed/multiomic_modeling/predictor_matrices/dosages/
