#!/bin/bash
#PBS -S /bin/bash
#PBS -l walltime=36:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=30gb
#PBS -d /home/ryan/software/TOPMED/Proteome/dapg_elasticnet
#PBS -e /home/ryan/topmed/multiomic_modeling/modeling_scripts/logs/${PBS_JOBNAME}.err
#PBS -o /home/ryan/topmed/multiomic_modeling/modeling_scripts/logs/${PBS_JOBNAME}.out

Rscript \
/home/ryan/topmed/multiomic_modeling/modeling_scripts/TOPMED_multiomic_call_elastic_net.R \
${chr}
